apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: mp-flux
spec:
  tls:
  - secretName: ssl-cert
  rules:
  - http:
      paths:
      - backend:
          serviceName: locations-service
          servicePort: 8080
        path: /api/v1/locations
      - backend:
          serviceName: locations-service
          servicePort: 8080
        path: /api/v1/locations/*
      - backend:
          serviceName: locations-service
          servicePort: 8080
        path: /api/v1/locations/country
      - backend:
          serviceName: locations-service
          servicePort: 8080
        path: /api/v1/locations/country/*
      - backend:
          serviceName: user-reviews
          servicePort: 8080
        path: /api/v1/reviews
      - backend:
          serviceName: user-reviews
          servicePort: 8080
        path: /api/v1/reviews/*
      - backend:
          serviceName: user-reviews
          servicePort: 8080
        path: /assets/*
      - backend:
          serviceName: poa-service
          servicePort: 8080
        path: /api/v1/poa
      - backend:
          serviceName: poa-service
          servicePort: 8080
        path: /api/v1/poa/*
      - backend:
          serviceName: auth-service
          servicePort: 8080
        path: /api/v1/auth
      - backend:
          serviceName: auth-service
          servicePort: 8080
        path: /api/v1/auth/*
      - backend:
          serviceName: norman
          servicePort: 8080
        path: /admin/norman
      - backend:
          serviceName: norman
          servicePort: 8080
        path: /admin/norman/*